"""
Seed script — populates DB with realistic Indian tech companies + people.
Run: python -m src.seed
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.database.core import engine, SessionLocal
from src.models.models import Base, Organization, Person

# ── Companies ──────────────────────────────────────────────────────────────────

ORGANIZATIONS = [
    {
        "id": "org_freshworks_001",
        "name": "Freshworks",
        "website_url": "https://www.freshworks.com",
        "linkedin_url": "https://www.linkedin.com/company/freshworks-inc",
        "twitter_url": "https://twitter.com/freshworks",
        "facebook_url": "https://facebook.com/freshworks",
        "phone": "+91 44 6667 8000",
        "sanitized_phone": "+914466678000",
        "primary_phone": {"number": "+91 44 6667 8000", "source": "Scraped", "sanitized_number": "+914466678000"},
        "languages": ["English", "Hindi"],
        "alexa_ranking": 3200,
        "linkedin_uid": "2152688",
        "founded_year": 2010,
        "logo_url": "https://logo.clearbit.com/freshworks.com",
        "primary_domain": "freshworks.com",
        "industry": "information technology & services",
        "estimated_num_employees": 7000,
        "keywords": ["crm", "customer support", "saas", "cloud", "ai", "helpdesk", "itsm"],
        "industries": ["information technology & services"],
        "secondary_industries": ["computer software"],
        "raw_address": "2950 S Delaware St Suite 201, San Mateo, California, United States",
        "street_address": "2950 S Delaware St Suite 201",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "postal_code": "600113",
        "country": "India",
        "short_description": "Freshworks makes it fast and easy for businesses to delight their customers and employees. We do this by taking a fresh approach to building and delivering software-as-a-service that is affordable, quick to implement, and designed for the end user.",
        "annual_revenue": 596000000,
        "annual_revenue_printed": "596M",
        "total_funding": 484000000,
        "total_funding_printed": "484M",
        "latest_funding_round_date": "2021-09-22T00:00:00.000+00:00",
        "latest_funding_stage": "IPO",
        "funding_events": [
            {"id": "fe_fw_001", "date": "2021-09-22T00:00:00.000+00:00", "type": "IPO", "investors": "Public Market", "amount": "1B", "currency": "$"},
            {"id": "fe_fw_002", "date": "2019-11-13T00:00:00.000+00:00", "type": "Series H", "investors": "Sequoia Capital, Accel", "amount": "150M", "currency": "$"},
        ],
        "technology_names": ["AWS", "Python", "React", "Kubernetes", "Salesforce", "Stripe", "AI", "Google Cloud"],
        "current_technologies": [
            {"uid": "aws", "name": "AWS", "category": "Cloud Services"},
            {"uid": "python", "name": "Python", "category": "Frameworks and Programming Languages"},
            {"uid": "react", "name": "React", "category": "Frameworks and Programming Languages"},
            {"uid": "kubernetes", "name": "Kubernetes", "category": "DevOps"},
            {"uid": "ai", "name": "AI", "category": "Other"},
        ],
    },
    {
        "id": "org_zoho_001",
        "name": "Zoho Corporation",
        "website_url": "https://www.zoho.com",
        "linkedin_url": "https://www.linkedin.com/company/zoho-corporation",
        "twitter_url": "https://twitter.com/zoho",
        "facebook_url": "https://facebook.com/zoho",
        "phone": "+91 44 6711 8000",
        "sanitized_phone": "+914467118000",
        "primary_phone": {"number": "+91 44 6711 8000", "source": "Scraped", "sanitized_number": "+914467118000"},
        "languages": ["English", "Tamil"],
        "alexa_ranking": 520,
        "linkedin_uid": "19912",
        "founded_year": 1996,
        "logo_url": "https://logo.clearbit.com/zoho.com",
        "primary_domain": "zoho.com",
        "industry": "computer software",
        "estimated_num_employees": 15000,
        "keywords": ["crm", "erp", "cloud software", "saas", "office suite", "ai", "devops"],
        "industries": ["computer software"],
        "secondary_industries": ["information technology & services"],
        "raw_address": "Estancia IT Park, GST Road, Kelambakkam, Chennai, Tamil Nadu 603202, India",
        "street_address": "Estancia IT Park, GST Road",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "postal_code": "603202",
        "country": "India",
        "short_description": "Zoho Corporation is a technology company that makes an extensive suite of business software. Zoho Office Suite is the company's primary product and competes directly with Google Workspace and Microsoft 365.",
        "annual_revenue": 1000000000,
        "annual_revenue_printed": "1B",
        "total_funding": 0,
        "total_funding_printed": "Bootstrapped",
        "latest_funding_round_date": None,
        "latest_funding_stage": "Bootstrapped",
        "funding_events": [],
        "technology_names": ["Python", "Java", "React", "AWS", "Azure", "AI", "PostgreSQL"],
        "current_technologies": [
            {"uid": "python", "name": "Python", "category": "Frameworks and Programming Languages"},
            {"uid": "java", "name": "Java", "category": "Frameworks and Programming Languages"},
            {"uid": "aws", "name": "AWS", "category": "Cloud Services"},
            {"uid": "azure", "name": "Azure", "category": "Cloud Services"},
            {"uid": "ai", "name": "AI", "category": "Other"},
        ],
    },
    {
        "id": "org_infosys_001",
        "name": "Infosys",
        "website_url": "https://www.infosys.com",
        "linkedin_url": "https://www.linkedin.com/company/infosys",
        "twitter_url": "https://twitter.com/infosys",
        "facebook_url": "https://facebook.com/Infosys",
        "phone": "+91 80 2852 0261",
        "sanitized_phone": "+918028520261",
        "primary_phone": {"number": "+91 80 2852 0261", "source": "Scraped", "sanitized_number": "+918028520261"},
        "languages": ["English", "Hindi"],
        "alexa_ranking": 2800,
        "linkedin_uid": "1283",
        "founded_year": 1981,
        "publicly_traded_symbol": "INFY",
        "publicly_traded_exchange": "NYSE",
        "logo_url": "https://logo.clearbit.com/infosys.com",
        "primary_domain": "infosys.com",
        "industry": "information technology & services",
        "estimated_num_employees": 320000,
        "keywords": ["digital transformation", "cloud", "ai", "devops", "devsecops", "consulting", "it services", "observability"],
        "industries": ["information technology & services"],
        "secondary_industries": ["management consulting"],
        "raw_address": "Electronics City, Hosur Road, Bengaluru, Karnataka 560100, India",
        "street_address": "Electronics City, Hosur Road",
        "city": "Bengaluru",
        "state": "Karnataka",
        "postal_code": "560100",
        "country": "India",
        "short_description": "Infosys is a global leader in next-generation digital services and consulting. We enable clients in 50+ countries to navigate their digital transformation.",
        "annual_revenue": 18209000000,
        "annual_revenue_printed": "18.2B",
        "total_funding": 0,
        "total_funding_printed": "Public",
        "latest_funding_round_date": None,
        "latest_funding_stage": "Public",
        "funding_events": [],
        "technology_names": ["AWS", "Azure", "GCP", "Kubernetes", "AI", "Python", "Java", "DevSecOps", "Terraform"],
        "current_technologies": [
            {"uid": "aws", "name": "AWS", "category": "Cloud Services"},
            {"uid": "azure", "name": "Azure", "category": "Cloud Services"},
            {"uid": "gcp", "name": "GCP", "category": "Cloud Services"},
            {"uid": "kubernetes", "name": "Kubernetes", "category": "DevOps"},
            {"uid": "ai", "name": "AI", "category": "Other"},
            {"uid": "terraform", "name": "Terraform", "category": "DevOps"},
        ],
    },
    {
        "id": "org_razorpay_001",
        "name": "Razorpay",
        "website_url": "https://razorpay.com",
        "linkedin_url": "https://www.linkedin.com/company/razorpay",
        "twitter_url": "https://twitter.com/Razorpay",
        "facebook_url": "https://facebook.com/razorpay",
        "phone": "+91 80 6160 6161",
        "sanitized_phone": "+918061606161",
        "primary_phone": {"number": "+91 80 6160 6161", "source": "Scraped", "sanitized_number": "+918061606161"},
        "languages": ["English", "Hindi"],
        "alexa_ranking": 1800,
        "linkedin_uid": "5151167",
        "founded_year": 2014,
        "logo_url": "https://logo.clearbit.com/razorpay.com",
        "primary_domain": "razorpay.com",
        "industry": "financial services",
        "estimated_num_employees": 3500,
        "keywords": ["fintech", "payments", "saas", "cloud", "ai", "banking", "api"],
        "industries": ["financial services"],
        "secondary_industries": ["computer software"],
        "raw_address": "SJR Cyber Laskar, Hosur Road, Bengaluru, Karnataka 560068, India",
        "street_address": "SJR Cyber Laskar",
        "city": "Bengaluru",
        "state": "Karnataka",
        "postal_code": "560068",
        "country": "India",
        "short_description": "Razorpay is a full-stack financial solutions company that helps businesses accept, process, and disburse payments. It is the only payments solution in India that allows businesses to access all payment modes.",
        "annual_revenue": 480000000,
        "annual_revenue_printed": "480M",
        "total_funding": 741500000,
        "total_funding_printed": "741.5M",
        "latest_funding_round_date": "2021-12-19T00:00:00.000+00:00",
        "latest_funding_stage": "Series F",
        "funding_events": [
            {"id": "fe_rp_001", "date": "2021-12-19T00:00:00.000+00:00", "type": "Series F", "investors": "Lone Pine Capital, Alkeon Capital", "amount": "375M", "currency": "$"},
            {"id": "fe_rp_002", "date": "2020-10-12T00:00:00.000+00:00", "type": "Series D", "investors": "GIC, Matrix Partners", "amount": "100M", "currency": "$"},
        ],
        "technology_names": ["AWS", "Python", "Go", "Kubernetes", "AI", "PostgreSQL", "Redis"],
        "current_technologies": [
            {"uid": "aws", "name": "AWS", "category": "Cloud Services"},
            {"uid": "python", "name": "Python", "category": "Frameworks and Programming Languages"},
            {"uid": "kubernetes", "name": "Kubernetes", "category": "DevOps"},
            {"uid": "redis", "name": "Redis", "category": "Databases"},
            {"uid": "ai", "name": "AI", "category": "Other"},
        ],
    },
    {
        "id": "org_browserstack_001",
        "name": "BrowserStack",
        "website_url": "https://www.browserstack.com",
        "linkedin_url": "https://www.linkedin.com/company/browserstack",
        "twitter_url": "https://twitter.com/browserstack",
        "facebook_url": "https://facebook.com/browserstack",
        "phone": "+1 855 490 1618",
        "sanitized_phone": "+18554901618",
        "primary_phone": {"number": "+1 855 490 1618", "source": "Scraped", "sanitized_number": "+18554901618"},
        "languages": ["English"],
        "alexa_ranking": 4100,
        "linkedin_uid": "2637994",
        "founded_year": 2011,
        "logo_url": "https://logo.clearbit.com/browserstack.com",
        "primary_domain": "browserstack.com",
        "industry": "computer software",
        "estimated_num_employees": 1500,
        "keywords": ["testing", "automation", "cloud", "devops", "ci/cd", "saas", "devsecops"],
        "industries": ["computer software"],
        "secondary_industries": ["information technology & services"],
        "raw_address": "4th Floor, Accelyst Solutions, Mumbai, Maharashtra 400013, India",
        "street_address": "4th Floor, Accelyst Solutions",
        "city": "Mumbai",
        "state": "Maharashtra",
        "postal_code": "400013",
        "country": "India",
        "short_description": "BrowserStack is the world's leading software testing platform powering over two million tests daily across 19 global data centers.",
        "annual_revenue": 200000000,
        "annual_revenue_printed": "200M",
        "total_funding": 206000000,
        "total_funding_printed": "206M",
        "latest_funding_round_date": "2021-06-16T00:00:00.000+00:00",
        "latest_funding_stage": "Series B",
        "funding_events": [
            {"id": "fe_bs_001", "date": "2021-06-16T00:00:00.000+00:00", "type": "Series B", "investors": "Insight Partners", "amount": "200M", "currency": "$"},
        ],
        "technology_names": ["AWS", "Python", "Node.js", "React", "Kubernetes", "AI", "Selenium"],
        "current_technologies": [
            {"uid": "aws", "name": "AWS", "category": "Cloud Services"},
            {"uid": "python", "name": "Python", "category": "Frameworks and Programming Languages"},
            {"uid": "kubernetes", "name": "Kubernetes", "category": "DevOps"},
            {"uid": "ai", "name": "AI", "category": "Other"},
        ],
    },
    {
        "id": "org_wipro_001",
        "name": "Wipro",
        "website_url": "https://www.wipro.com",
        "linkedin_url": "https://www.linkedin.com/company/wipro",
        "twitter_url": "https://twitter.com/Wipro",
        "facebook_url": "https://facebook.com/wipro",
        "phone": "+91 80 2844 0011",
        "sanitized_phone": "+918028440011",
        "primary_phone": {"number": "+91 80 2844 0011", "source": "Scraped", "sanitized_number": "+918028440011"},
        "languages": ["English", "Hindi"],
        "alexa_ranking": 5200,
        "linkedin_uid": "11388",
        "founded_year": 1945,
        "publicly_traded_symbol": "WIT",
        "publicly_traded_exchange": "NYSE",
        "logo_url": "https://logo.clearbit.com/wipro.com",
        "primary_domain": "wipro.com",
        "industry": "information technology & services",
        "estimated_num_employees": 258000,
        "keywords": ["cloud", "ai", "devsecops", "consulting", "digital transformation", "observability", "sre"],
        "industries": ["information technology & services"],
        "secondary_industries": ["management consulting"],
        "raw_address": "Doddakannelli, Sarjapur Road, Bengaluru, Karnataka 560035, India",
        "street_address": "Doddakannelli, Sarjapur Road",
        "city": "Bengaluru",
        "state": "Karnataka",
        "postal_code": "560035",
        "country": "India",
        "short_description": "Wipro Limited is a leading technology services and consulting company focused on building innovative solutions that address clients' most complex digital transformation needs.",
        "annual_revenue": 11158000000,
        "annual_revenue_printed": "11.2B",
        "total_funding": 0,
        "total_funding_printed": "Public",
        "latest_funding_round_date": None,
        "latest_funding_stage": "Public",
        "funding_events": [],
        "technology_names": ["AWS", "Azure", "GCP", "AI", "Kubernetes", "Terraform", "Python"],
        "current_technologies": [
            {"uid": "aws", "name": "AWS", "category": "Cloud Services"},
            {"uid": "azure", "name": "Azure", "category": "Cloud Services"},
            {"uid": "kubernetes", "name": "Kubernetes", "category": "DevOps"},
            {"uid": "terraform", "name": "Terraform", "category": "DevOps"},
            {"uid": "ai", "name": "AI", "category": "Other"},
        ],
    },
    {
        "id": "org_swiggy_001",
        "name": "Swiggy",
        "website_url": "https://www.swiggy.com",
        "linkedin_url": "https://www.linkedin.com/company/swiggy-in",
        "twitter_url": "https://twitter.com/Swiggy",
        "facebook_url": "https://facebook.com/swiggy.in",
        "phone": "+91 80 6746 6000",
        "sanitized_phone": "+918067466000",
        "primary_phone": {"number": "+91 80 6746 6000", "source": "Scraped", "sanitized_number": "+918067466000"},
        "languages": ["English", "Hindi"],
        "alexa_ranking": 900,
        "linkedin_uid": "5284414",
        "founded_year": 2014,
        "logo_url": "https://logo.clearbit.com/swiggy.com",
        "primary_domain": "swiggy.com",
        "industry": "internet",
        "estimated_num_employees": 5000,
        "keywords": ["food delivery", "cloud kitchen", "ai", "machine learning", "logistics", "platform"],
        "industries": ["internet"],
        "secondary_industries": ["consumer goods"],
        "raw_address": "3rd Floor, RmZ Ecoworld, Outer Ring Road, Bengaluru, Karnataka 560103, India",
        "street_address": "3rd Floor, RmZ Ecoworld",
        "city": "Bengaluru",
        "state": "Karnataka",
        "postal_code": "560103",
        "country": "India",
        "short_description": "Swiggy is India's leading on-demand delivery platform. With a tech-first approach to logistics and a solution-first approach to consumer needs, Swiggy is transforming the way India eats and lives.",
        "annual_revenue": 1200000000,
        "annual_revenue_printed": "1.2B",
        "total_funding": 3625000000,
        "total_funding_printed": "3.6B",
        "latest_funding_round_date": "2024-11-13T00:00:00.000+00:00",
        "latest_funding_stage": "IPO",
        "funding_events": [
            {"id": "fe_sw_001", "date": "2024-11-13T00:00:00.000+00:00", "type": "IPO", "investors": "Public Market", "amount": "1.35B", "currency": "$"},
            {"id": "fe_sw_002", "date": "2022-01-17T00:00:00.000+00:00", "type": "Series J", "investors": "Invesco, Baron Capital", "amount": "700M", "currency": "$"},
        ],
        "technology_names": ["AWS", "Python", "Go", "Kubernetes", "AI", "Kafka", "Redis"],
        "current_technologies": [
            {"uid": "aws", "name": "AWS", "category": "Cloud Services"},
            {"uid": "python", "name": "Python", "category": "Frameworks and Programming Languages"},
            {"uid": "kubernetes", "name": "Kubernetes", "category": "DevOps"},
            {"uid": "ai", "name": "AI", "category": "Other"},
            {"uid": "kafka", "name": "Kafka", "category": "Data Streaming"},
        ],
    },
    {
        "id": "org_meesho_001",
        "name": "Meesho",
        "website_url": "https://meesho.com",
        "linkedin_url": "https://www.linkedin.com/company/meesho",
        "twitter_url": "https://twitter.com/Meesho_Official",
        "facebook_url": "https://facebook.com/meesho",
        "phone": "+91 80 6178 0000",
        "sanitized_phone": "+918061780000",
        "primary_phone": {"number": "+91 80 6178 0000", "source": "Scraped", "sanitized_number": "+918061780000"},
        "languages": ["English", "Hindi"],
        "alexa_ranking": 600,
        "linkedin_uid": "10905775",
        "founded_year": 2015,
        "logo_url": "https://logo.clearbit.com/meesho.com",
        "primary_domain": "meesho.com",
        "industry": "internet",
        "estimated_num_employees": 3000,
        "keywords": ["ecommerce", "social commerce", "ai", "machine learning", "supply chain", "cloud"],
        "industries": ["internet"],
        "secondary_industries": ["retail"],
        "raw_address": "Pinnacle, Bannerghatta Road, Bengaluru, Karnataka 560029, India",
        "street_address": "Pinnacle, Bannerghatta Road",
        "city": "Bengaluru",
        "state": "Karnataka",
        "postal_code": "560029",
        "country": "India",
        "short_description": "Meesho is India's fastest growing e-commerce company. It is the most downloaded shopping app in India and enables 150M+ customers to shop online.",
        "annual_revenue": 775000000,
        "annual_revenue_printed": "775M",
        "total_funding": 1360000000,
        "total_funding_printed": "1.36B",
        "latest_funding_round_date": "2021-09-16T00:00:00.000+00:00",
        "latest_funding_stage": "Series F",
        "funding_events": [
            {"id": "fe_me_001", "date": "2021-09-16T00:00:00.000+00:00", "type": "Series F", "investors": "Fidelity, B Capital", "amount": "570M", "currency": "$"},
        ],
        "technology_names": ["AWS", "Python", "Go", "React", "Kubernetes", "AI", "Spark"],
        "current_technologies": [
            {"uid": "aws", "name": "AWS", "category": "Cloud Services"},
            {"uid": "python", "name": "Python", "category": "Frameworks and Programming Languages"},
            {"uid": "kubernetes", "name": "Kubernetes", "category": "DevOps"},
            {"uid": "ai", "name": "AI", "category": "Other"},
        ],
    },
    {
        "id": "org_zepto_001",
        "name": "Zepto",
        "website_url": "https://www.zeptonow.com",
        "linkedin_url": "https://www.linkedin.com/company/zepto-now",
        "twitter_url": "https://twitter.com/ZeptoNow",
        "facebook_url": "https://facebook.com/zeptonow",
        "phone": "+91 22 6248 0000",
        "sanitized_phone": "+912262480000",
        "primary_phone": {"number": "+91 22 6248 0000", "source": "Scraped", "sanitized_number": "+912262480000"},
        "languages": ["English", "Hindi"],
        "alexa_ranking": 1200,
        "linkedin_uid": "76290578",
        "founded_year": 2021,
        "logo_url": "https://logo.clearbit.com/zeptonow.com",
        "primary_domain": "zeptonow.com",
        "industry": "internet",
        "estimated_num_employees": 2000,
        "keywords": ["quick commerce", "grocery delivery", "ai", "logistics", "cloud", "supply chain"],
        "industries": ["internet"],
        "secondary_industries": ["consumer goods"],
        "raw_address": "Koramangala, Bengaluru, Karnataka 560034, India",
        "street_address": "Koramangala",
        "city": "Mumbai",
        "state": "Maharashtra",
        "postal_code": "400001",
        "country": "India",
        "short_description": "Zepto is India's fastest growing quick commerce company delivering groceries and essentials in 10 minutes. With a network of dark stores, Zepto is redefining last-mile delivery.",
        "annual_revenue": 1700000000,
        "annual_revenue_printed": "1.7B",
        "total_funding": 1800000000,
        "total_funding_printed": "1.8B",
        "latest_funding_round_date": "2024-06-20T00:00:00.000+00:00",
        "latest_funding_stage": "Series G",
        "funding_events": [
            {"id": "fe_ze_001", "date": "2024-06-20T00:00:00.000+00:00", "type": "Series G", "investors": "General Catalyst, StepStone", "amount": "665M", "currency": "$"},
        ],
        "technology_names": ["AWS", "Python", "Go", "Kubernetes", "AI", "Redis", "Kafka"],
        "current_technologies": [
            {"uid": "aws", "name": "AWS", "category": "Cloud Services"},
            {"uid": "python", "name": "Python", "category": "Frameworks and Programming Languages"},
            {"uid": "kubernetes", "name": "Kubernetes", "category": "DevOps"},
            {"uid": "ai", "name": "AI", "category": "Other"},
        ],
    },
    {
        "id": "org_cred_001",
        "name": "CRED",
        "website_url": "https://cred.club",
        "linkedin_url": "https://www.linkedin.com/company/credit-card-management-india",
        "twitter_url": "https://twitter.com/CRED_club",
        "facebook_url": "https://facebook.com/cred.club",
        "phone": "+91 80 6178 9000",
        "sanitized_phone": "+918061789000",
        "primary_phone": {"number": "+91 80 6178 9000", "source": "Scraped", "sanitized_number": "+918061789000"},
        "languages": ["English", "Hindi"],
        "alexa_ranking": 2100,
        "linkedin_uid": "18755246",
        "founded_year": 2018,
        "logo_url": "https://logo.clearbit.com/cred.club",
        "primary_domain": "cred.club",
        "industry": "financial services",
        "estimated_num_employees": 1500,
        "keywords": ["fintech", "credit card", "payments", "ai", "machine learning", "rewards"],
        "industries": ["financial services"],
        "secondary_industries": ["internet"],
        "raw_address": "Dream11, Bengaluru, Karnataka 560001, India",
        "street_address": "Bengaluru",
        "city": "Bengaluru",
        "state": "Karnataka",
        "postal_code": "560001",
        "country": "India",
        "short_description": "CRED is a members-only credit card bill payment platform that rewards its members for paying their credit card bills on time.",
        "annual_revenue": 300000000,
        "annual_revenue_printed": "300M",
        "total_funding": 800000000,
        "total_funding_printed": "800M",
        "latest_funding_round_date": "2022-10-05T00:00:00.000+00:00",
        "latest_funding_stage": "Series F",
        "funding_events": [
            {"id": "fe_cr_001", "date": "2022-10-05T00:00:00.000+00:00", "type": "Series F", "investors": "GIC, Sofina", "amount": "140M", "currency": "$"},
        ],
        "technology_names": ["AWS", "Python", "Kotlin", "React Native", "AI", "ML", "Redis"],
        "current_technologies": [
            {"uid": "aws", "name": "AWS", "category": "Cloud Services"},
            {"uid": "python", "name": "Python", "category": "Frameworks and Programming Languages"},
            {"uid": "ai", "name": "AI", "category": "Other"},
            {"uid": "redis", "name": "Redis", "category": "Databases"},
        ],
    },
]

# ── People ─────────────────────────────────────────────────────────────────────

PEOPLE = [
    # Freshworks people
    {
        "id": "person_fw_001",
        "organization_id": "org_freshworks_001",
        "first_name": "Girish",
        "last_name": "Mathrubootham",
        "last_name_obfuscated": "Ma***m",
        "name": "Girish Mathrubootham",
        "title": "CEO & Founder",
        "email": "girish@freshworks.com",
        "email_status": "verified",
        "photo_url": "https://media.licdn.com/dms/image/girish.jpg",
        "linkedin_url": "https://www.linkedin.com/in/girish1",
        "headline": "Founder & CEO at Freshworks",
        "city": "Chennai", "state": "Tamil Nadu", "country": "India",
        "seniority": "founder",
        "departments": ["c_suite"],
        "subdepartments": ["executive", "founder"],
        "functions": ["entrepreneurship"],
        "has_email": True, "has_direct_phone": "Yes",
        "last_refreshed_at": "2025-06-01T00:00:00.000+00:00",
        "phone_numbers": [{"raw_number": "+91 98400 12345", "sanitized_number": "+919840012345", "type": "mobile", "position": 0, "status": "valid_number", "dnc_status": None}],
        "employment_history": [
            {"_id": "eh_fw_001", "current": True, "organization_id": "org_freshworks_001", "organization_name": "Freshworks", "start_date": "2010-01-01", "title": "CEO & Founder", "id": "eh_fw_001", "key": "eh_fw_001"},
            {"_id": "eh_fw_002", "current": False, "organization_id": None, "organization_name": "Zoho", "end_date": "2010-01-01", "start_date": "2001-01-01", "title": "VP Product Management", "id": "eh_fw_002", "key": "eh_fw_002"},
        ],
    },
    {
        "id": "person_fw_002",
        "organization_id": "org_freshworks_001",
        "first_name": "Suresh",
        "last_name": "Sambandam",
        "last_name_obfuscated": "Sa***m",
        "name": "Suresh Sambandam",
        "title": "CTO",
        "email": "suresh@freshworks.com",
        "email_status": "verified",
        "photo_url": None,
        "linkedin_url": "https://www.linkedin.com/in/suresh-sambandam",
        "headline": "CTO at Freshworks",
        "city": "Chennai", "state": "Tamil Nadu", "country": "India",
        "seniority": "c_suite",
        "departments": ["engineering"],
        "subdepartments": ["engineering_leadership"],
        "functions": ["engineering"],
        "has_email": True, "has_direct_phone": "Yes",
        "last_refreshed_at": "2025-05-15T00:00:00.000+00:00",
        "phone_numbers": [{"raw_number": "+91 98400 54321", "sanitized_number": "+919840054321", "type": "mobile", "position": 0, "status": "valid_number", "dnc_status": None}],
        "employment_history": [
            {"_id": "eh_fw_003", "current": True, "organization_id": "org_freshworks_001", "organization_name": "Freshworks", "start_date": "2015-01-01", "title": "CTO", "id": "eh_fw_003", "key": "eh_fw_003"},
        ],
    },
    # Zoho people
    {
        "id": "person_zo_001",
        "organization_id": "org_zoho_001",
        "first_name": "Sridhar",
        "last_name": "Vembu",
        "last_name_obfuscated": "Ve***u",
        "name": "Sridhar Vembu",
        "title": "CEO & Co-Founder",
        "email": "sridhar@zohocorp.com",
        "email_status": "verified",
        "photo_url": None,
        "linkedin_url": "https://www.linkedin.com/in/sridharvembu",
        "headline": "CEO at Zoho Corporation",
        "city": "Chennai", "state": "Tamil Nadu", "country": "India",
        "seniority": "founder",
        "departments": ["c_suite"],
        "subdepartments": ["executive", "founder"],
        "functions": ["entrepreneurship"],
        "has_email": True, "has_direct_phone": "Yes",
        "last_refreshed_at": "2025-06-01T00:00:00.000+00:00",
        "phone_numbers": [{"raw_number": "+91 44 6711 8001", "sanitized_number": "+914467118001", "type": "work", "position": 0, "status": "valid_number", "dnc_status": None}],
        "employment_history": [
            {"_id": "eh_zo_001", "current": True, "organization_id": "org_zoho_001", "organization_name": "Zoho Corporation", "start_date": "1996-01-01", "title": "CEO & Co-Founder", "id": "eh_zo_001", "key": "eh_zo_001"},
        ],
    },
    {
        "id": "person_zo_002",
        "organization_id": "org_zoho_001",
        "first_name": "Raju",
        "last_name": "Vegesna",
        "last_name_obfuscated": "Ve***a",
        "name": "Raju Vegesna",
        "title": "Chief Evangelist",
        "email": "raju@zohocorp.com",
        "email_status": "verified",
        "photo_url": None,
        "linkedin_url": "https://www.linkedin.com/in/rajuvegesna",
        "headline": "Chief Evangelist at Zoho",
        "city": "Chennai", "state": "Tamil Nadu", "country": "India",
        "seniority": "c_suite",
        "departments": ["marketing"],
        "subdepartments": ["marketing_leadership"],
        "functions": ["marketing"],
        "has_email": True, "has_direct_phone": "Yes",
        "last_refreshed_at": "2025-04-20T00:00:00.000+00:00",
        "phone_numbers": [],
        "employment_history": [
            {"_id": "eh_zo_002", "current": True, "organization_id": "org_zoho_001", "organization_name": "Zoho Corporation", "start_date": "2000-01-01", "title": "Chief Evangelist", "id": "eh_zo_002", "key": "eh_zo_002"},
        ],
    },
    # Infosys people
    {
        "id": "person_in_001",
        "organization_id": "org_infosys_001",
        "first_name": "Salil",
        "last_name": "Parekh",
        "last_name_obfuscated": "Pa***h",
        "name": "Salil Parekh",
        "title": "CEO & Managing Director",
        "email": "salil.parekh@infosys.com",
        "email_status": "verified",
        "photo_url": None,
        "linkedin_url": "https://www.linkedin.com/in/salilparekh",
        "headline": "CEO at Infosys",
        "city": "Bengaluru", "state": "Karnataka", "country": "India",
        "seniority": "c_suite",
        "departments": ["c_suite"],
        "subdepartments": ["executive"],
        "functions": ["operations"],
        "has_email": True, "has_direct_phone": "Yes",
        "last_refreshed_at": "2025-06-01T00:00:00.000+00:00",
        "phone_numbers": [{"raw_number": "+91 80 2852 0001", "sanitized_number": "+918028520001", "type": "work", "position": 0, "status": "valid_number", "dnc_status": None}],
        "employment_history": [
            {"_id": "eh_in_001", "current": True, "organization_id": "org_infosys_001", "organization_name": "Infosys", "start_date": "2018-01-02", "title": "CEO & Managing Director", "id": "eh_in_001", "key": "eh_in_001"},
            {"_id": "eh_in_002", "current": False, "organization_name": "Capgemini", "end_date": "2017-12-31", "start_date": "2000-01-01", "title": "CEO", "id": "eh_in_002", "key": "eh_in_002"},
        ],
    },
    {
        "id": "person_in_002",
        "organization_id": "org_infosys_001",
        "first_name": "Mohit",
        "last_name": "Joshi",
        "last_name_obfuscated": "Jo***i",
        "name": "Mohit Joshi",
        "title": "President",
        "email": "mohit.joshi@infosys.com",
        "email_status": "verified",
        "photo_url": None,
        "linkedin_url": "https://www.linkedin.com/in/mohit-joshi",
        "headline": "President at Infosys",
        "city": "Bengaluru", "state": "Karnataka", "country": "India",
        "seniority": "c_suite",
        "departments": ["c_suite"],
        "subdepartments": ["executive"],
        "functions": ["operations"],
        "has_email": True, "has_direct_phone": "Yes",
        "last_refreshed_at": "2025-05-10T00:00:00.000+00:00",
        "phone_numbers": [],
        "employment_history": [
            {"_id": "eh_in_003", "current": True, "organization_id": "org_infosys_001", "organization_name": "Infosys", "start_date": "2008-01-01", "title": "President", "id": "eh_in_003", "key": "eh_in_003"},
        ],
    },
    # Razorpay people
    {
        "id": "person_rp_001",
        "organization_id": "org_razorpay_001",
        "first_name": "Harshil",
        "last_name": "Mathur",
        "last_name_obfuscated": "Ma***r",
        "name": "Harshil Mathur",
        "title": "CEO & Co-Founder",
        "email": "harshil@razorpay.com",
        "email_status": "verified",
        "photo_url": None,
        "linkedin_url": "https://www.linkedin.com/in/harshilmathur",
        "headline": "CEO at Razorpay",
        "city": "Bengaluru", "state": "Karnataka", "country": "India",
        "seniority": "founder",
        "departments": ["c_suite"],
        "subdepartments": ["executive", "founder"],
        "functions": ["entrepreneurship"],
        "has_email": True, "has_direct_phone": "Yes",
        "last_refreshed_at": "2025-06-01T00:00:00.000+00:00",
        "phone_numbers": [{"raw_number": "+91 98765 43210", "sanitized_number": "+919876543210", "type": "mobile", "position": 0, "status": "valid_number", "dnc_status": None}],
        "employment_history": [
            {"_id": "eh_rp_001", "current": True, "organization_id": "org_razorpay_001", "organization_name": "Razorpay", "start_date": "2014-01-01", "title": "CEO & Co-Founder", "id": "eh_rp_001", "key": "eh_rp_001"},
        ],
    },
    {
        "id": "person_rp_002",
        "organization_id": "org_razorpay_001",
        "first_name": "Shashank",
        "last_name": "Kumar",
        "last_name_obfuscated": "Ku***r",
        "name": "Shashank Kumar",
        "title": "CTO & Co-Founder",
        "email": "shashank@razorpay.com",
        "email_status": "verified",
        "photo_url": None,
        "linkedin_url": "https://www.linkedin.com/in/shashank-kumar-razorpay",
        "headline": "CTO at Razorpay",
        "city": "Bengaluru", "state": "Karnataka", "country": "India",
        "seniority": "founder",
        "departments": ["engineering"],
        "subdepartments": ["engineering_leadership", "founder"],
        "functions": ["engineering", "entrepreneurship"],
        "has_email": True, "has_direct_phone": "Yes",
        "last_refreshed_at": "2025-05-20T00:00:00.000+00:00",
        "phone_numbers": [],
        "employment_history": [
            {"_id": "eh_rp_002", "current": True, "organization_id": "org_razorpay_001", "organization_name": "Razorpay", "start_date": "2014-01-01", "title": "CTO & Co-Founder", "id": "eh_rp_002", "key": "eh_rp_002"},
        ],
    },
    # BrowserStack people
    {
        "id": "person_bs_001",
        "organization_id": "org_browserstack_001",
        "first_name": "Ritesh",
        "last_name": "Arora",
        "last_name_obfuscated": "Ar***a",
        "name": "Ritesh Arora",
        "title": "CEO & Co-Founder",
        "email": "ritesh@browserstack.com",
        "email_status": "verified",
        "photo_url": None,
        "linkedin_url": "https://www.linkedin.com/in/ritesh-arora-browserstack",
        "headline": "CEO at BrowserStack",
        "city": "Mumbai", "state": "Maharashtra", "country": "India",
        "seniority": "founder",
        "departments": ["c_suite"],
        "subdepartments": ["executive", "founder"],
        "functions": ["entrepreneurship"],
        "has_email": True, "has_direct_phone": "Yes",
        "last_refreshed_at": "2025-06-01T00:00:00.000+00:00",
        "phone_numbers": [{"raw_number": "+91 22 6248 0001", "sanitized_number": "+912262480001", "type": "work", "position": 0, "status": "valid_number", "dnc_status": None}],
        "employment_history": [
            {"_id": "eh_bs_001", "current": True, "organization_id": "org_browserstack_001", "organization_name": "BrowserStack", "start_date": "2011-01-01", "title": "CEO & Co-Founder", "id": "eh_bs_001", "key": "eh_bs_001"},
        ],
    },
    # Wipro people
    {
        "id": "person_wi_001",
        "organization_id": "org_wipro_001",
        "first_name": "Thierry",
        "last_name": "Delaporte",
        "last_name_obfuscated": "De***e",
        "name": "Thierry Delaporte",
        "title": "CEO & Managing Director",
        "email": "thierry.delaporte@wipro.com",
        "email_status": "verified",
        "photo_url": None,
        "linkedin_url": "https://www.linkedin.com/in/thierry-delaporte",
        "headline": "CEO at Wipro",
        "city": "Bengaluru", "state": "Karnataka", "country": "India",
        "seniority": "c_suite",
        "departments": ["c_suite"],
        "subdepartments": ["executive"],
        "functions": ["operations"],
        "has_email": True, "has_direct_phone": "Yes",
        "last_refreshed_at": "2025-06-01T00:00:00.000+00:00",
        "phone_numbers": [{"raw_number": "+91 80 2844 0001", "sanitized_number": "+918028440001", "type": "work", "position": 0, "status": "valid_number", "dnc_status": None}],
        "employment_history": [
            {"_id": "eh_wi_001", "current": True, "organization_id": "org_wipro_001", "organization_name": "Wipro", "start_date": "2020-07-06", "title": "CEO & Managing Director", "id": "eh_wi_001", "key": "eh_wi_001"},
        ],
    },
]


def seed():
    print("Creating tables...")
    Base.metadata.create_all(bind=engine)

    db = SessionLocal()
    try:
        # clear existing data
        db.query(Person).delete()
        db.query(Organization).delete()
        db.commit()
        print("Cleared existing data.")

        # seed organizations
        for org_data in ORGANIZATIONS:
            org = Organization(**org_data)
            db.add(org)
        db.commit()
        print(f"Seeded {len(ORGANIZATIONS)} organizations.")

        # seed people
        for person_data in PEOPLE:
            person = Person(**person_data)
            db.add(person)
        db.commit()
        print(f"Seeded {len(PEOPLE)} people.")

        print("✅ Seed complete!")

    except Exception as e:
        db.rollback()
        print(f"❌ Seed failed: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
